config/routes.rb
Proj7C::Application.routes.draw do
  

  get "main/home"

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'view', to: 'users#show', as:'view'
  get 'users/update_profile'
  get 'users/edit'
  
  get 'search', to: 'users#search', as: 'search'

  match 'blogs/show_comments/:id' => 'blogs#show_comments', :as => :show_comments
 
  resources :blogs do
    member do
      post :comment_add
      get :show_comments
    end
  end
  get 'blogs/show_comments', as:'comments'
  resources :users
  resources :sessions
  root to: 'Main#home'
  
  
   

  

   match ':controller(/:action(/:id))(.:format)'
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :commentbody, :user_id
  has_and_belongs_to_many :blogs
  
  validate :commentbody, :presence => true
  validates_uniqueness_of :commentbody
  
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  has_one :User
  
  attr_accessible :user_id, :comment, :profile_picture
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :profile
  has_many :blogs
  has_secure_password
  
  attr_accessible :username, :email, :password, :password_confirmation, :user_id, :comment, :profile_picture
  
  validates_uniqueness_of :email, :username

  def to_param
    username
  end
  validate :password_length, :on => :create
   
  def password_length
    if password.length < 5 
      errors.add(:password, "Must be greater than 5 characters")
    end
  end
  
  def username_and_email
    [username, email].join('-')
  end
  
  def username_and_email=(umail)
    split = umail.split('-')
    self.username = split.first
    self.email = split.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery
  
private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
	
  end
  helper_method :current_user
  
  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
  
 
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  # GET /blogs
  # GET /blogs.json
  before_filter  :authorize, only:[:edit, :update, :new, :index]

  def index
    @blogs = Blog.all
	
    respond_to do |format|
	
      format.html # index.html.erb
      format.json { render json: @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
   #this should never work; intentional, and cruel.
	@blog = Blog.find_by_title(params[:id])
 #
  
		format.html { redirect_to(root_url, :notice => 'Invalid URL please stop ')}
		if @blog.blank?
	  		format.html { redirect_to(root_url, :notice => 'Invalid URL please stop ')}
	  	else
			format.html { redirect_to(root_url, :notice => 'Invalid URL please stop ')}
			format.html # show.html.erb
			format.json { render json: @blog }
		end
    
  end
  
  def show_comments
   #this should never work; intentional, and cruel.
	@blog = Blog.find(params[:id])
  
  @blogcomments = @blog.comments
  respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @blog; @blogcomments }
    end
  end
  #Comments code
  def comment_add
    unless session[:user_id] == nil and !verify_recaptcha()
      @blog = Blog.find(params[:id])
      @comment = Comment.new;
      @comment.commentbody = (params[:commentbody])
      @comment.user_id = (params[:user_id])
      @blog.comments << @comment
      redirect_to :back
    else
	  ##not working
	  flash[:notice] = 'Your input did not match the ReCaptcha. Please try again.'
      redirect_to :back
    end
  end
  
  
  #end of comments code
  # GET /blogs/new
  # GET /blogs/new.json
  
  def new
    @blog = Blog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog }
    end
  end
  
  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
	if (@blog.user_id != session[:user_id])	
		redirect_to(user_path(current_user.username), :notice=> "Blog post with this ID either doesn't belong to you or does not exist")
	end
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(params[:blog])
	@recaptchaError
    respond_to do |format|
      if verify_recaptcha() and @blog.save
        format.html { redirect_to user_path(current_user.username), notice: 'Post was successfully created.' }
        format.json { render json: @blog, status: :created, location: @blog }
		@recaptchaError = ''
      else
		flash[:notice] = 'Your input did not match the ReCaptcha. Please try again.'
        format.html { render action: "new" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.json
  def update
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to user_path(current_user.username), notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end
  

  
  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @post = Blog.find(params[:id])
    @post.destroy

  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(current_user.username)#index, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  
  def new
	@user = User.new
	@userprofile = Profile.new
	
  end
  
  def create
	@user = User.new(params[:user])
	
	if @user.save
	  @userprofile = Profile.new
	  @userprofile.user_id = @user.id
	  @userprofile.save
	  session[:user_id] = @user.id
	  
	  redirect_to root_url, notice: "Sign up complete!"
	else
	  render "new"
	end
  end
  
  def index
	@users = User.all
	
	 respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
	end
  end
  
  def show
	@usersblog = User.find_by_username(params[:id])
	#@usersblog = User.find_by_username(@search)
	respond_to do |format|
	  if @usersblog.blank?
		format.html { redirect_to(root_url, :notice => 'User not found')}
	    
	  else
	  
		format.html # show.html.erb
		format.json { render json: @usersblog }
	  end
    end
  end	
  
  
  def edit
	if session[:user_id]
	  @user = User.find(session[:user_id])
	else
		redirect_to(root_url, :notice=> 'please log in before attempting this')
	end
  end
  
  def update
	@user = User.find(session[:user_id])
	
	
	#@profile = @user.build_profile
	#@usersprofile = User.find(session[:user_id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html{ redirect_to user_path(current_user.username), notice: 'Profile updated.' }
        format.json { head :no_content}
      else
      	format.html { render action: "edit"}
      	format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
		
    end
  end
  
  def search
    if params[:search_text].blank?
      @search_error = 'Please enter at least one character into the search'
    elsif params[:search_parameter] == "username"
     @match_term = "%" + params[:search_text] + "%"
      @results = User.where("UPPER(username) Like UPPER(?)", @match_term).all
    elsif params[:search_parameter] == "email"
      @match_term = "%" + params[:search_text] + "%"
      @results = User.where("UPPER(email) Like UPPER(?)", @match_term).all
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body  %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %> Not implemented yet, feel free to leave blank!
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="field">
	<% @cd = Date.today.to_s %>
    
    <%= f.hidden_field :Date_Created, :value => @cd %>
  </div>
  <div class="cap">
  <%= recaptcha_tags %> <%= @recaptchaErrors %>
  </div>
  <div id="notice"><%= notice %></div>
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/blogs/destroy.js.erb
$("#post<%=  @post.id %>").fadeOut();

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>


<%= link_to 'Back', user_path(current_user.username) %>

app/views/blogs/index.html.erb
<%= link_to "view your blog the way others would see it", user_path(current_user.username)%>
<br />
<br />
<br />
<br />
<h1>Listing <%=current_user.username%>'s blog posts</h1>

<table>
  <tr>
	
    <th>Title</th>
    <th>Body</th>
    <th>Image</th>
    <th>Post Date</th>
    <th>Last Update Date</th>
    <th></th>
  </tr>

<% @blogs.each do |blog| %>
<% if blog.user_id == current_user.id %>
  <tr>
	
	
    <td><%= blog.title %></td>
    <td><%= blog.body %></td>
    <td><%= blog.image %></td>
	<td><%= blog.Date_Created  %></td>
	<td><%= blog.Date_Updated  %></td>
    <td><%= link_to 'Show', blog %></td>
    <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
    <td><%= link_to 'Destroy', blog, confirm: 'Are you sure?', method: :delete %></td>
	<% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', user_path(current_user.username) %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @blog.title %>
</p>

<p>
  <b>Body:</b>
  <%= @blog.body %>
</p>

<p>
  <b>Image:</b>
  <%= @blog.image %>
</p>

<p>
  <b>ID:</b>
  <%= @blog.user_id %>
</p>


<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/show_comments.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>


<p>
  
  <%= @blog.image %>
</p>
<p>
  
<h2> <%= @blog.title %></h2>
 
</p>
<br>
<p>
  <%= @blog.body %>
</p>
<br>
<hr>
<% if !@blog.comments.empty? %>
<table>
     <% @blog.comments.reverse.each do |comment|%>
      <tr >
        <td>
          <p id ="comment">
           <%if User.find(comment.user_id)%>
             <% @users = User.find(comment.user_id)%>
             <%= @users.username %> said...
           <%  end %>
          </p>
        
        </td>
      </tr>
      <tr>
        <td>
          <p id="commentbody">
            <%= comment.commentbody%>
          </p>
        </td>
      </tr>
      <tr>
        <td>
          <p id="commentdate">
            <%=  comment.created_at%>
          </p>
          
        </td>
      </tr>
      <tr>
        <td>
      
        </td>
      </tr>
      <%end%>
</table>

<%  else %>
<br>
<br>
<strong>
No current comments, be the first  leave a comment!
</strong>
<% end %>
<%= form_tag(comment_add_blog_path()) %>
<br>
<p>
<%= text_area_tag :commentbody %>
<%= hidden_field_tag :user_id, session[:user_id] %>
</p>
  <div class="cap">
  <%= recaptcha_tags %> <%= @recaptchaErrors %>
  </div>
  <div id="notice"><%= notice %></div>
<p>
<%= submit_tag 'Submit Comment' %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleblog</title>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
  <div id="container">
     <div id="user_header">

        <% if current_user %>
          Logged in as <%= current_user.username %>.
          <%= link_to "Log Out", logout_path %>
		  
		  <%= link_to "Edit Profile", users_edit_path %>
		  <%= link_to "Blog", user_path(current_user.username) %>
                  <%= link_to "Search", search_path %>
                  <%= link_to "List of Users", users_path %>  
        <% else %>
          <%= link_to "Sign Up", signup_path %>
          <%= link_to "Log In", login_path %>
	  <%= link_to "Search", search_path %>
          <%= link_to "List of Users", users_path %>  	 
          
        <% end %>
       
	</div>
	<br>
	<br>
   
      <%= yield %>
    </div>
	
	
  </body>
  <div id="footer">
    &copy; 2013 Yanushik Cerda
  </div>
</html>

app/views/main/home.html.erb
<div id="home">
<h1>Welcome to Simple Blog!</h1></br>
<p> just want a place to put your thoughts without having to "personalize"
and all that other silly stuff?</p> <h3>Simple Blog is the place for you </h3> </br><p>To get started
just click signup on the top right of this page. If you already have an account, click on log in.
</p>
</br>
<h2>Please edit your profile after logging in!</h2>
<p>
Click the Edit Profile button on the top right to edit your profile. Not using an image on your profile may affect
formatting.
</p>
</br>
<h2>Just want to check out someone else's blog?</h2><p> Click on List of viewers on the top right or use the search to find someone specific</p></br>
</div>

app/views/users/_profileform.html.erb
<%= form_for @user do |f| %>
  <div class="field">
    <%= f.label :user_id %><br /> 
  </div>
  <div class="field">
    <%= f.label :comment%><br />
    <%= f.text_area :comment, :maxlength => 250%>
    
  </div>
  <div class="field">
    <%= f.label :profile_picture %><br />
    <%= f.text_field :profile_picture %> Use a link to the image (Ex: http://dapictures.com/banana.jpg)
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'profileform' %>

app/views/users/index.html.erb
<br>
<br>
<h1 style="text-align:center">CURRENTLY REGISTERED USERS</h1>

<table id="userlist" style="text-align:center">
  <tr>
    <th>Username</th>
    <th>Link to blog</th> 
  </tr>

<% @users.each do |user| %>

  <tr>
    <td><%= user.username %></td>
    <td> <%= link_to "view", user_path(user.username)%></td>
  </tr>
<% end %>
</table>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_explanation">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

app/views/users/search.html.erb
<%= form_tag search_path, :method => 'get' do %>
<h1>Search</h1>
<br>
<p>
<%= label_tag :search_text %>
<%= text_field_tag :search_text %>
&nbsp
<%= label_tag 'By'  %>
<%= select_tag :search_parameter, raw(["<option>username</option>","<option>email</option>"]) %>
</p>

<%= submit_tag 'Search' %>

<% end %>
<br>
<%= @search_error %>
<% if @results %>
<table style="text-align:center">
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th>Link to blog</th>
    
  </tr>
  <% @results.each do |results|%>
  <tr>
    <td><%= results.username %></td>
    <td><%= results.email  %></td>
    <td> <%= link_to "view", user_path(results.username)%></td>
  </tr>

  <% end %>
  </table>
<%end%>

app/views/users/show.html.erb
<div id = "blog_profile_container">
<%if @usersblog.profile_picture != nil%>
  <%= image_tag(@usersblog.profile_picture, :class =>"profile") %><br><br>
<%else%>
  <%= image_tag "defaultpicture.png" %>
<%end%>
Email: <br><%= @usersblog.email %><br><br>
Username: <br><%= @usersblog.username %><br><br>
<pre-wrap>
<% if @usersblog.comment != nil %>
<% Sanitize.clean(@usersblog.comment.html_safe, {
					:elements =>['iframe'],
					:attributes => {'iframe' => ['src','width','height','frameborder' 'allowfullscreen']}})%>
<%= @usersblog.comment.html_safe %>
<% else %>
  When you add a comment it will show up here!
<%end%>
</pre-wrap>
</div>
<div id ="blog_container">
<p>
<%if @usersblog.id == session[:user_id]%>
	<%= link_to "New Post", new_blog_path %>
<%end%>
</p>

<% @usersblog.blogs.sort! {|a,b| rel = a.created_at <=> b.created_at} %>
<% @usersblog.blogs.reverse.each do |post| %>
<div>
<table id="post<%=  post.id %>">
<tr>
<td><h2><%= post.title %></h2></td>
</tr>
<tr>
<td id="timestamp">Posted on: <%= post.Date_Created %></td>
</tr>

<tr>
   
<td style = "width:1000px;">
<pre>
<% Sanitize.clean(post.body, :add_attributes =>{
					:elements =>['iframe','img'],
					:attributes => {'iframe' => ['src','width','height','frameborder' 'allowfullscreen'],
									'img' => ['a','href','width','height','src']}})%>
<%= post.body.html_safe %>

</pre>
</tr>
<tr>
<p id="commentcount">
  <% @sample = post.comments.count.to_s %>
  <%if @usersblog.id == session[:user_id]%>
  <td><%= link_to @sample+ " Comments", show_comments_path(post) %></td><td><%= link_to "Edit", edit_blog_path(post) %>
      <%= link_to 'Destroy', post, data:{confirm: 'Are you sure?'}, method: :delete, remote: true %></td>
  <%end%>
</p>

</td>
</tr>

<tr>
  <td><hr><td>
</tr>
</div>
</table>
<%end%>

  
</div>